import { Provider } from "@/context/provider"
import "@/app/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Provider>
          {children}
        </Provider>
      </body>
      </html>
  )
}
